spring:
  application:
    name: transaction
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        show_sql: ${SPRING_JPA_SHOW_SQL}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

  server:
    port: ${SPRING_APP_PORT}